Repository openkcm/common-sdk, pull requests merged in 2025-07, with the labels that each got.

#54 fix(audit): replace cmkid with systemid in cmkswitch
  pkg/otlp/audit/events.go
  pkg/otlp/audit/events_test.go
Labels: release, minor

#57 feat: add support for basic authentication on the SecretRef struct
  pkg/commoncfg/config.go
Labels: release, feature

#70 fix: move the feature gates field at level of application
  pkg/commoncfg/config.go
Labels: bug, feature
