Repository openkcm/common-sdk, pull requests merged in 2025-09, with the labels that each got.

#90 feat: combine load mtls config
  pkg/commoncfg/loader.go
  pkg/otlp/opentelemetry.go
Labels: feature

#101 fix: remove grouping for service environment and name
  pkg/commoncfg/attributes.go
  pkg/logger/logger.go
  pkg/otlp/attributes.go
  pkg/otlp/attributes_test.go
  pkg/otlp/opentelemetry.go
Labels: bug, tests

#121 feat: add filesystem watcher and notify which file was modified over the handlers
  go.mod
  pkg/fs/watcher.go
  pkg/fs/watcher_test.go
Labels: dependencies, feature, tests

#120 fix: build information is passed as base64(<encoded value>)
  pkg/commoncfg/config.go
  pkg/commoncfg/loader.go
  pkg/utils/values.go
  pkg/utils/values_test.go
Labels: bug, dependencies, tests, build

#128 fix: add documentation for common fs and storage
  pkg/commonfs/loader/loader.go
  pkg/commonfs/watcher/watcher.go
  pkg/storage/keyvalue/memory_storage.go
  pkg/storage/keyvalue/storage.go
  pkg/storage/keyvalue/types.go
Labels: bug

#132 fix: commonfs fixes and introduced a notifier
  go.mod
  go.sum
  pkg/commonfs/loader/loader.go
  pkg/commonfs/loader/loader_test.go
  pkg/commonfs/notifier/notifier.go
  pkg/commonfs/watcher/watcher.go
  pkg/commonfs/watcher/watcher_test.go
  pkg/storage/keyvalue/memory_storage.go
  pkg/storage/keyvalue/storage.go
  pkg/utils/files.go
Labels: bug, dependencies, tests
