Repository openkcm/common-sdk, pull requests merged in 2025-08, with the labels that each got.

#74 fix: stop error on created status
  pkg/otlp/audit/comm.go
Labels: bug

#76 feat: add new type of credentials oauth2 based on client id and clien…
  pkg/commoncfg/config.go
  pkg/commoncfg/loader.go
  pkg/otlp/opentelemetry.go
Labels: feature

#77 fix: adjusts the lints
  internal/testutils/mutator.go
  pkg/auth/clientdata.go
  pkg/auth/clientdata_test.go
  pkg/commoncfg/loader.go
  pkg/commoncfg/loader_test.go
  pkg/commongrpc/client.go
  pkg/grpcpool/export_test.go
  pkg/grpcpool/grpcpool.go
  pkg/grpcpool/grpcpool_test.go
  pkg/health/checker.go
  pkg/health/checker_test.go
  pkg/health/config_test.go
  pkg/health/grpc_client.go
  pkg/health/grpc_client_test.go
  pkg/health/handler.go
  pkg/logger/gdpr-middleware.go
  pkg/logger/gdpr-middleware_test.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
  pkg/otlp/attributes.go
  pkg/otlp/audit/comm.go
  pkg/otlp/audit/consts.go
  pkg/otlp/audit/eventproperties.go
  pkg/otlp/audit/eventproperties_test.go
  pkg/otlp/audit/events.go
  pkg/otlp/audit/events_test.go
  pkg/otlp/audit/logger.go
  pkg/otlp/audit/logger_test.go
  pkg/otlp/opentelemetry_test.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: bug, tests

#79 fix: include the mtls into the oauth2 secret type
  pkg/commoncfg/config.go
Labels: bug

#85 fix: refactor the oauth2 credentials and add the pointers set of func…
  pkg/commoncfg/config.go
  pkg/pointers/pointers.go
Labels: bug

#88 fix: change the value to reference for couple functions
  pkg/commoncfg/loader.go
  pkg/commoncfg/loader_test.go
  pkg/otlp/audit/logger.go
  pkg/otlp/opentelemetry.go
Labels: bug, tests
